version: '3.8'

services:
  web:
    build: .
    container_name: lms
    ports:
      - "3000:3000" 
      - "5555:5555"  
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next  # Assuming this is the correct path, adjust if necessary
    environment:
      DATABASE_URL: "mysql://root:my-secret-pw@db:3306/lms_database"
      NEXT_WEBPACK_USEPOLLING: "1"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    container_name: mysql_lms
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: lms_database 
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root --password=$MYSQL_ROOT_PASSWORD"]
      interval: 1s
      retries: 120

volumes:
  mysql_data:
